# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/mmqgis_geocode_web_service_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mmqgis_geocode_web_service_form(object):
    def setupUi(self, mmqgis_geocode_web_service_form):
        mmqgis_geocode_web_service_form.setObjectName("mmqgis_geocode_web_service_form")
        mmqgis_geocode_web_service_form.setWindowModality(QtCore.Qt.ApplicationModal)
        mmqgis_geocode_web_service_form.setEnabled(True)
        mmqgis_geocode_web_service_form.resize(549, 454)
        mmqgis_geocode_web_service_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_geocode_web_service_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(mmqgis_geocode_web_service_form)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.input_csv_name = gui.QgsFileWidget(mmqgis_geocode_web_service_form)
        self.input_csv_name.setObjectName("input_csv_name")
        self.verticalLayout.addWidget(self.input_csv_name)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.parameter_name_1 = QtWidgets.QLabel(mmqgis_geocode_web_service_form)
        self.parameter_name_1.setObjectName("parameter_name_1")
        self.gridLayout.addWidget(self.parameter_name_1, 0, 0, 1, 1)
        self.parameter_attribute_1 = QtWidgets.QComboBox(mmqgis_geocode_web_service_form)
        self.parameter_attribute_1.setObjectName("parameter_attribute_1")
        self.gridLayout.addWidget(self.parameter_attribute_1, 1, 0, 1, 1)
        self.parameter_attribute_2 = QtWidgets.QComboBox(mmqgis_geocode_web_service_form)
        self.parameter_attribute_2.setObjectName("parameter_attribute_2")
        self.gridLayout.addWidget(self.parameter_attribute_2, 1, 2, 1, 1)
        self.parameter_name_3 = QtWidgets.QLabel(mmqgis_geocode_web_service_form)
        self.parameter_name_3.setObjectName("parameter_name_3")
        self.gridLayout.addWidget(self.parameter_name_3, 2, 0, 1, 1)
        self.parameter_name_2 = QtWidgets.QLabel(mmqgis_geocode_web_service_form)
        self.parameter_name_2.setObjectName("parameter_name_2")
        self.gridLayout.addWidget(self.parameter_name_2, 0, 2, 1, 1)
        self.parameter_attribute_4 = QtWidgets.QComboBox(mmqgis_geocode_web_service_form)
        self.parameter_attribute_4.setObjectName("parameter_attribute_4")
        self.gridLayout.addWidget(self.parameter_attribute_4, 3, 2, 1, 1)
        self.parameter_name_4 = QtWidgets.QLabel(mmqgis_geocode_web_service_form)
        self.parameter_name_4.setObjectName("parameter_name_4")
        self.gridLayout.addWidget(self.parameter_name_4, 2, 2, 1, 1)
        self.parameter_attribute_3 = QtWidgets.QComboBox(mmqgis_geocode_web_service_form)
        self.parameter_attribute_3.setObjectName("parameter_attribute_3")
        self.gridLayout.addWidget(self.parameter_attribute_3, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_8 = QtWidgets.QLabel(mmqgis_geocode_web_service_form)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.web_service = QtWidgets.QComboBox(mmqgis_geocode_web_service_form)
        self.web_service.setObjectName("web_service")
        self.verticalLayout.addWidget(self.web_service)
        self.api_key_label = QtWidgets.QLabel(mmqgis_geocode_web_service_form)
        self.api_key_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.api_key_label.setObjectName("api_key_label")
        self.verticalLayout.addWidget(self.api_key_label)
        self.api_key = QtWidgets.QLineEdit(mmqgis_geocode_web_service_form)
        self.api_key.setObjectName("api_key")
        self.verticalLayout.addWidget(self.api_key)
        self.label_9 = QtWidgets.QLabel(mmqgis_geocode_web_service_form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.duplicate_handling = QtWidgets.QComboBox(mmqgis_geocode_web_service_form)
        self.duplicate_handling.setObjectName("duplicate_handling")
        self.verticalLayout.addWidget(self.duplicate_handling)
        self.label = QtWidgets.QLabel(mmqgis_geocode_web_service_form)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.output_file_name = gui.QgsFileWidget(mmqgis_geocode_web_service_form)
        self.output_file_name.setObjectName("output_file_name")
        self.verticalLayout.addWidget(self.output_file_name)
        self.label_5 = QtWidgets.QLabel(mmqgis_geocode_web_service_form)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.not_found_file_name = gui.QgsFileWidget(mmqgis_geocode_web_service_form)
        self.not_found_file_name.setObjectName("not_found_file_name")
        self.verticalLayout.addWidget(self.not_found_file_name)
        self.status = QtWidgets.QProgressBar(mmqgis_geocode_web_service_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(mmqgis_geocode_web_service_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_geocode_web_service_form)
        self.buttonBox.accepted.connect(mmqgis_geocode_web_service_form.accept)
        self.buttonBox.rejected.connect(mmqgis_geocode_web_service_form.reject)
        QtCore.QMetaObject.connectSlotsByName(mmqgis_geocode_web_service_form)
        mmqgis_geocode_web_service_form.setTabOrder(self.parameter_attribute_1, self.parameter_attribute_2)
        mmqgis_geocode_web_service_form.setTabOrder(self.parameter_attribute_2, self.parameter_attribute_3)
        mmqgis_geocode_web_service_form.setTabOrder(self.parameter_attribute_3, self.buttonBox)

    def retranslateUi(self, mmqgis_geocode_web_service_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_geocode_web_service_form.setWindowTitle(_translate("mmqgis_geocode_web_service_form", "Web Service Geocode"))
        self.label_2.setText(_translate("mmqgis_geocode_web_service_form", "Input CSV File (UTF-8)"))
        self.parameter_name_1.setText(_translate("mmqgis_geocode_web_service_form", "Address"))
        self.parameter_name_3.setText(_translate("mmqgis_geocode_web_service_form", "State"))
        self.parameter_name_2.setText(_translate("mmqgis_geocode_web_service_form", "City"))
        self.parameter_name_4.setText(_translate("mmqgis_geocode_web_service_form", "Country"))
        self.label_8.setText(_translate("mmqgis_geocode_web_service_form", "Web Service"))
        self.api_key_label.setText(_translate("mmqgis_geocode_web_service_form", "API Key"))
        self.label_9.setText(_translate("mmqgis_geocode_web_service_form", "Duplicate Handling"))
        self.label.setText(_translate("mmqgis_geocode_web_service_form", "Output File Name"))
        self.label_5.setText(_translate("mmqgis_geocode_web_service_form", "Not Found Output List"))

from qgis import gui
