# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/mmqgis_spatial_join_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mmqgis_spatial_join_form(object):
    def setupUi(self, mmqgis_spatial_join_form):
        mmqgis_spatial_join_form.setObjectName("mmqgis_spatial_join_form")
        mmqgis_spatial_join_form.setWindowModality(QtCore.Qt.ApplicationModal)
        mmqgis_spatial_join_form.setEnabled(True)
        mmqgis_spatial_join_form.resize(567, 444)
        mmqgis_spatial_join_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_spatial_join_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(mmqgis_spatial_join_form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.target_layer_name = QtWidgets.QComboBox(mmqgis_spatial_join_form)
        self.target_layer_name.setObjectName("target_layer_name")
        self.verticalLayout.addWidget(self.target_layer_name)
        self.label_5 = QtWidgets.QLabel(mmqgis_spatial_join_form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.spatial_operation = QtWidgets.QComboBox(mmqgis_spatial_join_form)
        self.spatial_operation.setObjectName("spatial_operation")
        self.spatial_operation.addItem("")
        self.spatial_operation.addItem("")
        self.spatial_operation.addItem("")
        self.verticalLayout.addWidget(self.spatial_operation)
        self.label_3 = QtWidgets.QLabel(mmqgis_spatial_join_form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.join_layer_name = QtWidgets.QComboBox(mmqgis_spatial_join_form)
        self.join_layer_name.setObjectName("join_layer_name")
        self.verticalLayout.addWidget(self.join_layer_name)
        self.label_7 = QtWidgets.QLabel(mmqgis_spatial_join_form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.field_names = QtWidgets.QListWidget(mmqgis_spatial_join_form)
        self.field_names.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.field_names.setObjectName("field_names")
        item = QtWidgets.QListWidgetItem()
        self.field_names.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.field_names.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.field_names.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.field_names.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.field_names.addItem(item)
        self.verticalLayout.addWidget(self.field_names)
        self.label_6 = QtWidgets.QLabel(mmqgis_spatial_join_form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.field_operation = QtWidgets.QComboBox(mmqgis_spatial_join_form)
        self.field_operation.setObjectName("field_operation")
        self.verticalLayout.addWidget(self.field_operation)
        self.label = QtWidgets.QLabel(mmqgis_spatial_join_form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.output_file_name = gui.QgsFileWidget(mmqgis_spatial_join_form)
        self.output_file_name.setObjectName("output_file_name")
        self.verticalLayout.addWidget(self.output_file_name)
        self.status = QtWidgets.QProgressBar(mmqgis_spatial_join_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(mmqgis_spatial_join_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_spatial_join_form)
        self.buttonBox.accepted.connect(mmqgis_spatial_join_form.accept)
        self.buttonBox.rejected.connect(mmqgis_spatial_join_form.reject)
        QtCore.QMetaObject.connectSlotsByName(mmqgis_spatial_join_form)
        mmqgis_spatial_join_form.setTabOrder(self.target_layer_name, self.spatial_operation)
        mmqgis_spatial_join_form.setTabOrder(self.spatial_operation, self.join_layer_name)
        mmqgis_spatial_join_form.setTabOrder(self.join_layer_name, self.field_operation)
        mmqgis_spatial_join_form.setTabOrder(self.field_operation, self.field_names)
        mmqgis_spatial_join_form.setTabOrder(self.field_names, self.buttonBox)

    def retranslateUi(self, mmqgis_spatial_join_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_spatial_join_form.setWindowTitle(_translate("mmqgis_spatial_join_form", "Spatial Join"))
        self.label_4.setText(_translate("mmqgis_spatial_join_form", "Output Shape (Target) Layer"))
        self.label_5.setText(_translate("mmqgis_spatial_join_form", "Spatial Operation"))
        self.spatial_operation.setItemText(0, _translate("mmqgis_spatial_join_form", "Intersects"))
        self.spatial_operation.setItemText(1, _translate("mmqgis_spatial_join_form", "Within"))
        self.spatial_operation.setItemText(2, _translate("mmqgis_spatial_join_form", "Contains"))
        self.label_3.setText(_translate("mmqgis_spatial_join_form", "Data (Join) Layer"))
        self.label_7.setText(_translate("mmqgis_spatial_join_form", "Fields"))
        __sortingEnabled = self.field_names.isSortingEnabled()
        self.field_names.setSortingEnabled(False)
        item = self.field_names.item(0)
        item.setText(_translate("mmqgis_spatial_join_form", "Alpha"))
        item = self.field_names.item(1)
        item.setText(_translate("mmqgis_spatial_join_form", "Beta"))
        item = self.field_names.item(2)
        item.setText(_translate("mmqgis_spatial_join_form", "Gamma"))
        item = self.field_names.item(3)
        item.setText(_translate("mmqgis_spatial_join_form", "Delta"))
        item = self.field_names.item(4)
        item.setText(_translate("mmqgis_spatial_join_form", "Epsilon"))
        self.field_names.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("mmqgis_spatial_join_form", "Field Operation"))
        self.label.setText(_translate("mmqgis_spatial_join_form", "Output File Name"))

from qgis import gui
