# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/mmqgis_geocode_street_layer_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mmqgis_geocode_street_layer_form(object):
    def setupUi(self, mmqgis_geocode_street_layer_form):
        mmqgis_geocode_street_layer_form.setObjectName("mmqgis_geocode_street_layer_form")
        mmqgis_geocode_street_layer_form.setWindowModality(QtCore.Qt.ApplicationModal)
        mmqgis_geocode_street_layer_form.setEnabled(True)
        mmqgis_geocode_street_layer_form.resize(548, 504)
        mmqgis_geocode_street_layer_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_geocode_street_layer_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.input_csv_name = gui.QgsFileWidget(mmqgis_geocode_street_layer_form)
        self.input_csv_name.setObjectName("input_csv_name")
        self.verticalLayout.addWidget(self.input_csv_name)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.zip_column = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.zip_column.setObjectName("zip_column")
        self.gridLayout.addWidget(self.zip_column, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_17.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 3, 1, 1)
        self.number_column = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.number_column.setObjectName("number_column")
        self.gridLayout.addWidget(self.number_column, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.street_name_column = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.street_name_column.setObjectName("street_name_column")
        self.gridLayout.addWidget(self.street_name_column, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_3 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.input_layer_name = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.input_layer_name.setObjectName("input_layer_name")
        self.verticalLayout.addWidget(self.input_layer_name)
        self.label_6 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.street_name_attr = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.street_name_attr.setObjectName("street_name_attr")
        self.verticalLayout.addWidget(self.street_name_attr)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_12 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 1, 1, 1)
        self.left_to_attr = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.left_to_attr.setObjectName("left_to_attr")
        self.gridLayout_3.addWidget(self.left_to_attr, 4, 0, 1, 1)
        self.right_to_attr = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.right_to_attr.setObjectName("right_to_attr")
        self.gridLayout_3.addWidget(self.right_to_attr, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 1, 1, 1)
        self.right_from_attr = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.right_from_attr.setObjectName("right_from_attr")
        self.gridLayout_3.addWidget(self.right_from_attr, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 5, 1, 1, 1)
        self.left_from_attr = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.left_from_attr.setObjectName("left_from_attr")
        self.gridLayout_3.addWidget(self.left_from_attr, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.left_zip_attr = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.left_zip_attr.setObjectName("left_zip_attr")
        self.gridLayout_3.addWidget(self.left_zip_attr, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 0, 1, 1)
        self.right_zip_attr = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.right_zip_attr.setObjectName("right_zip_attr")
        self.gridLayout_3.addWidget(self.right_zip_attr, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 3, 1, 1)
        self.from_x_attr = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.from_x_attr.setObjectName("from_x_attr")
        self.gridLayout_3.addWidget(self.from_x_attr, 2, 2, 1, 1)
        self.from_y_attr = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.from_y_attr.setObjectName("from_y_attr")
        self.gridLayout_3.addWidget(self.from_y_attr, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 3, 1, 1)
        self.to_x_attr = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.to_x_attr.setObjectName("to_x_attr")
        self.gridLayout_3.addWidget(self.to_x_attr, 4, 2, 1, 1)
        self.to_y_attr = QtWidgets.QComboBox(mmqgis_geocode_street_layer_form)
        self.to_y_attr.setObjectName("to_y_attr")
        self.gridLayout_3.addWidget(self.to_y_attr, 4, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 5, 3, 1, 1)
        self.setback = QtWidgets.QLineEdit(mmqgis_geocode_street_layer_form)
        self.setback.setObjectName("setback")
        self.gridLayout_3.addWidget(self.setback, 6, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.label = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.output_file_name = gui.QgsFileWidget(mmqgis_geocode_street_layer_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_file_name.sizePolicy().hasHeightForWidth())
        self.output_file_name.setSizePolicy(sizePolicy)
        self.output_file_name.setObjectName("output_file_name")
        self.verticalLayout.addWidget(self.output_file_name)
        self.label_5 = QtWidgets.QLabel(mmqgis_geocode_street_layer_form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.not_found_file_name = gui.QgsFileWidget(mmqgis_geocode_street_layer_form)
        self.not_found_file_name.setObjectName("not_found_file_name")
        self.verticalLayout.addWidget(self.not_found_file_name)
        self.status = QtWidgets.QProgressBar(mmqgis_geocode_street_layer_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(mmqgis_geocode_street_layer_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_geocode_street_layer_form)
        self.buttonBox.accepted.connect(mmqgis_geocode_street_layer_form.accept)
        self.buttonBox.rejected.connect(mmqgis_geocode_street_layer_form.reject)
        QtCore.QMetaObject.connectSlotsByName(mmqgis_geocode_street_layer_form)
        mmqgis_geocode_street_layer_form.setTabOrder(self.number_column, self.zip_column)
        mmqgis_geocode_street_layer_form.setTabOrder(self.zip_column, self.buttonBox)

    def retranslateUi(self, mmqgis_geocode_street_layer_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_geocode_street_layer_form.setWindowTitle(_translate("mmqgis_geocode_street_layer_form", "Geocode from Street Layer"))
        self.label_2.setText(_translate("mmqgis_geocode_street_layer_form", "Input CSV File (UTF-8)"))
        self.label_17.setText(_translate("mmqgis_geocode_street_layer_form", "ZIP Column (optional)"))
        self.label_16.setText(_translate("mmqgis_geocode_street_layer_form", "Number Column"))
        self.label_4.setText(_translate("mmqgis_geocode_street_layer_form", "Street Name Column"))
        self.label_3.setText(_translate("mmqgis_geocode_street_layer_form", "Street Layer"))
        self.label_6.setText(_translate("mmqgis_geocode_street_layer_form", "Street Name Attribute"))
        self.label_12.setText(_translate("mmqgis_geocode_street_layer_form", "Left From Number"))
        self.label_14.setText(_translate("mmqgis_geocode_street_layer_form", "Right From Number"))
        self.label_13.setText(_translate("mmqgis_geocode_street_layer_form", "Right To Number"))
        self.label_19.setText(_translate("mmqgis_geocode_street_layer_form", "Right ZIP (optional)"))
        self.label_11.setText(_translate("mmqgis_geocode_street_layer_form", "Left To Number"))
        self.label_18.setText(_translate("mmqgis_geocode_street_layer_form", "Left ZIP (optional)"))
        self.label_7.setText(_translate("mmqgis_geocode_street_layer_form", "From X Attribute"))
        self.label_8.setText(_translate("mmqgis_geocode_street_layer_form", "From Y Attribute"))
        self.label_9.setText(_translate("mmqgis_geocode_street_layer_form", "To X Attribute"))
        self.label_10.setText(_translate("mmqgis_geocode_street_layer_form", "To Y Attribute"))
        self.label_20.setText(_translate("mmqgis_geocode_street_layer_form", "Setback (Map Units)"))
        self.label.setText(_translate("mmqgis_geocode_street_layer_form", "Output File Name"))
        self.label_5.setText(_translate("mmqgis_geocode_street_layer_form", "Not Found Output List"))

from qgis import gui
