# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/mmqgis_grid_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mmqgis_grid_form(object):
    def setupUi(self, mmqgis_grid_form):
        mmqgis_grid_form.setObjectName("mmqgis_grid_form")
        mmqgis_grid_form.setWindowModality(QtCore.Qt.ApplicationModal)
        mmqgis_grid_form.setEnabled(True)
        mmqgis_grid_form.resize(551, 393)
        mmqgis_grid_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_grid_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.typelabel = QtWidgets.QLabel(mmqgis_grid_form)
        self.typelabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.typelabel.setObjectName("typelabel")
        self.verticalLayout.addWidget(self.typelabel)
        self.geometry_type = QtWidgets.QComboBox(mmqgis_grid_form)
        self.geometry_type.setObjectName("geometry_type")
        self.verticalLayout.addWidget(self.geometry_type)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(mmqgis_grid_form)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(mmqgis_grid_form)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(mmqgis_grid_form)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 1, 1, 1)
        self.x_spacing = QtWidgets.QLineEdit(mmqgis_grid_form)
        self.x_spacing.setObjectName("x_spacing")
        self.gridLayout_2.addWidget(self.x_spacing, 1, 0, 1, 1)
        self.y_spacing = QtWidgets.QLineEdit(mmqgis_grid_form)
        self.y_spacing.setObjectName("y_spacing")
        self.gridLayout_2.addWidget(self.y_spacing, 1, 1, 1, 1)
        self.units = QtWidgets.QComboBox(mmqgis_grid_form)
        self.units.setObjectName("units")
        self.gridLayout_2.addWidget(self.units, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.extent_label = QtWidgets.QLabel(mmqgis_grid_form)
        self.extent_label.setObjectName("extent_label")
        self.gridLayout.addWidget(self.extent_label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(mmqgis_grid_form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.extent_type = QtWidgets.QComboBox(mmqgis_grid_form)
        self.extent_type.setObjectName("extent_type")
        self.gridLayout.addWidget(self.extent_type, 1, 0, 1, 1)
        self.input_layer_name = QtWidgets.QComboBox(mmqgis_grid_form)
        self.input_layer_name.setObjectName("input_layer_name")
        self.gridLayout.addWidget(self.input_layer_name, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.x_right = QtWidgets.QLineEdit(mmqgis_grid_form)
        self.x_right.setObjectName("x_right")
        self.gridLayout_3.addWidget(self.x_right, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(mmqgis_grid_form)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(mmqgis_grid_form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(mmqgis_grid_form)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(mmqgis_grid_form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.y_bottom = QtWidgets.QLineEdit(mmqgis_grid_form)
        self.y_bottom.setObjectName("y_bottom")
        self.gridLayout_3.addWidget(self.y_bottom, 5, 1, 1, 1)
        self.x_left = QtWidgets.QLineEdit(mmqgis_grid_form)
        self.x_left.setObjectName("x_left")
        self.gridLayout_3.addWidget(self.x_left, 3, 0, 1, 1)
        self.y_top = QtWidgets.QLineEdit(mmqgis_grid_form)
        self.y_top.setObjectName("y_top")
        self.gridLayout_3.addWidget(self.y_top, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.label_13 = QtWidgets.QLabel(mmqgis_grid_form)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.output_file_name = gui.QgsFileWidget(mmqgis_grid_form)
        self.output_file_name.setObjectName("output_file_name")
        self.verticalLayout.addWidget(self.output_file_name)
        self.status = QtWidgets.QProgressBar(mmqgis_grid_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(mmqgis_grid_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_grid_form)
        self.buttonBox.accepted.connect(mmqgis_grid_form.accept)
        self.buttonBox.rejected.connect(mmqgis_grid_form.reject)
        QtCore.QMetaObject.connectSlotsByName(mmqgis_grid_form)
        mmqgis_grid_form.setTabOrder(self.geometry_type, self.x_spacing)
        mmqgis_grid_form.setTabOrder(self.x_spacing, self.y_spacing)
        mmqgis_grid_form.setTabOrder(self.y_spacing, self.units)
        mmqgis_grid_form.setTabOrder(self.units, self.extent_type)
        mmqgis_grid_form.setTabOrder(self.extent_type, self.input_layer_name)
        mmqgis_grid_form.setTabOrder(self.input_layer_name, self.x_right)
        mmqgis_grid_form.setTabOrder(self.x_right, self.y_bottom)

    def retranslateUi(self, mmqgis_grid_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_grid_form.setWindowTitle(_translate("mmqgis_grid_form", "Grid"))
        self.typelabel.setText(_translate("mmqgis_grid_form", "Geometry Type"))
        self.label_6.setText(_translate("mmqgis_grid_form", "X Spacing"))
        self.label_9.setText(_translate("mmqgis_grid_form", "Units"))
        self.label_8.setText(_translate("mmqgis_grid_form", "Y Spacing"))
        self.x_spacing.setText(_translate("mmqgis_grid_form", "100"))
        self.y_spacing.setText(_translate("mmqgis_grid_form", "100"))
        self.extent_label.setText(_translate("mmqgis_grid_form", "Extent"))
        self.label_7.setText(_translate("mmqgis_grid_form", "Layer"))
        self.x_right.setText(_translate("mmqgis_grid_form", "0"))
        self.label_10.setText(_translate("mmqgis_grid_form", "Top Y"))
        self.label_3.setText(_translate("mmqgis_grid_form", "Right X"))
        self.label_11.setText(_translate("mmqgis_grid_form", "Bottom Y"))
        self.label_2.setText(_translate("mmqgis_grid_form", "Left X"))
        self.y_bottom.setText(_translate("mmqgis_grid_form", "0"))
        self.x_left.setText(_translate("mmqgis_grid_form", "10"))
        self.y_top.setText(_translate("mmqgis_grid_form", "0"))
        self.label_13.setText(_translate("mmqgis_grid_form", "Output File Name"))
        self.output_file_name.setFilter(_translate("mmqgis_grid_form", "Shapefile (*.shp)"))

from qgis import gui
