# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/mmqgis_hub_lines_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mmqgis_hub_lines_form(object):
    def setupUi(self, mmqgis_hub_lines_form):
        mmqgis_hub_lines_form.setObjectName("mmqgis_hub_lines_form")
        mmqgis_hub_lines_form.setWindowModality(QtCore.Qt.ApplicationModal)
        mmqgis_hub_lines_form.setEnabled(True)
        mmqgis_hub_lines_form.resize(475, 312)
        mmqgis_hub_lines_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_hub_lines_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(mmqgis_hub_lines_form)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(mmqgis_hub_lines_form)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.hub_layer_name = QtWidgets.QComboBox(mmqgis_hub_lines_form)
        self.hub_layer_name.setObjectName("hub_layer_name")
        self.gridLayout_2.addWidget(self.hub_layer_name, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(mmqgis_hub_lines_form)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.hub_name_field = QtWidgets.QComboBox(mmqgis_hub_lines_form)
        self.hub_name_field.setObjectName("hub_name_field")
        self.gridLayout_2.addWidget(self.hub_name_field, 1, 1, 1, 1)
        self.spoke_layer_name = QtWidgets.QComboBox(mmqgis_hub_lines_form)
        self.spoke_layer_name.setObjectName("spoke_layer_name")
        self.gridLayout_2.addWidget(self.spoke_layer_name, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(mmqgis_hub_lines_form)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 1, 1, 1)
        self.spoke_hub_name_field = QtWidgets.QComboBox(mmqgis_hub_lines_form)
        self.spoke_hub_name_field.setObjectName("spoke_hub_name_field")
        self.gridLayout_2.addWidget(self.spoke_hub_name_field, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label_2 = QtWidgets.QLabel(mmqgis_hub_lines_form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.allocation_criteria = QtWidgets.QComboBox(mmqgis_hub_lines_form)
        self.allocation_criteria.setObjectName("allocation_criteria")
        self.verticalLayout.addWidget(self.allocation_criteria)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(mmqgis_hub_lines_form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(mmqgis_hub_lines_form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.output_geometry = QtWidgets.QComboBox(mmqgis_hub_lines_form)
        self.output_geometry.setObjectName("output_geometry")
        self.gridLayout.addWidget(self.output_geometry, 2, 0, 1, 1)
        self.distance_unit = QtWidgets.QComboBox(mmqgis_hub_lines_form)
        self.distance_unit.setObjectName("distance_unit")
        self.gridLayout.addWidget(self.distance_unit, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_13 = QtWidgets.QLabel(mmqgis_hub_lines_form)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.output_file_name = gui.QgsFileWidget(mmqgis_hub_lines_form)
        self.output_file_name.setObjectName("output_file_name")
        self.verticalLayout.addWidget(self.output_file_name)
        self.status = QtWidgets.QProgressBar(mmqgis_hub_lines_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(mmqgis_hub_lines_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_hub_lines_form)
        self.buttonBox.accepted.connect(mmqgis_hub_lines_form.accept)
        self.buttonBox.rejected.connect(mmqgis_hub_lines_form.reject)
        QtCore.QMetaObject.connectSlotsByName(mmqgis_hub_lines_form)
        mmqgis_hub_lines_form.setTabOrder(self.spoke_layer_name, self.hub_layer_name)
        mmqgis_hub_lines_form.setTabOrder(self.hub_layer_name, self.hub_name_field)
        mmqgis_hub_lines_form.setTabOrder(self.hub_name_field, self.output_geometry)
        mmqgis_hub_lines_form.setTabOrder(self.output_geometry, self.buttonBox)

    def retranslateUi(self, mmqgis_hub_lines_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_hub_lines_form.setWindowTitle(_translate("mmqgis_hub_lines_form", "Hub Lines"))
        self.label_4.setText(_translate("mmqgis_hub_lines_form", "Spoke Layer"))
        self.label_5.setText(_translate("mmqgis_hub_lines_form", "Hub Name Field"))
        self.label_3.setText(_translate("mmqgis_hub_lines_form", "Hub Layer"))
        self.label.setText(_translate("mmqgis_hub_lines_form", "Hub Name in Spoke Layer"))
        self.label_2.setText(_translate("mmqgis_hub_lines_form", "Allocation Criteria"))
        self.label_6.setText(_translate("mmqgis_hub_lines_form", "Output Geometry"))
        self.label_7.setText(_translate("mmqgis_hub_lines_form", "Distance Unit"))
        self.label_13.setText(_translate("mmqgis_hub_lines_form", "Output File Name"))
        self.output_file_name.setFilter(_translate("mmqgis_hub_lines_form", "Shapefile (*.shp);; GeoJSON (*.geojson);; KML (*.kml);; SQLite (*.sqlite);; GPKG (*.gpkg);; All Files (*.*)"))

from qgis import gui
