# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/mmqgis_attribute_export_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mmqgis_attribute_export_form(object):
    def setupUi(self, mmqgis_attribute_export_form):
        mmqgis_attribute_export_form.setObjectName("mmqgis_attribute_export_form")
        mmqgis_attribute_export_form.setWindowModality(QtCore.Qt.ApplicationModal)
        mmqgis_attribute_export_form.setEnabled(True)
        mmqgis_attribute_export_form.resize(400, 360)
        mmqgis_attribute_export_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_attribute_export_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(mmqgis_attribute_export_form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.input_layer_name = QtWidgets.QComboBox(mmqgis_attribute_export_form)
        self.input_layer_name.setObjectName("input_layer_name")
        self.verticalLayout.addWidget(self.input_layer_name)
        self.label_2 = QtWidgets.QLabel(mmqgis_attribute_export_form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.attributes = QtWidgets.QListWidget(mmqgis_attribute_export_form)
        self.attributes.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.attributes.setObjectName("attributes")
        item = QtWidgets.QListWidgetItem()
        self.attributes.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.attributes.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.attributes.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.attributes.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.attributes.addItem(item)
        self.verticalLayout.addWidget(self.attributes)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_terminator = QtWidgets.QComboBox(mmqgis_attribute_export_form)
        self.line_terminator.setObjectName("line_terminator")
        self.gridLayout.addWidget(self.line_terminator, 1, 2, 1, 1)
        self.decimal_mark = QtWidgets.QComboBox(mmqgis_attribute_export_form)
        self.decimal_mark.setObjectName("decimal_mark")
        self.gridLayout.addWidget(self.decimal_mark, 1, 1, 1, 1)
        self.field_delimiter = QtWidgets.QComboBox(mmqgis_attribute_export_form)
        self.field_delimiter.setObjectName("field_delimiter")
        self.gridLayout.addWidget(self.field_delimiter, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(mmqgis_attribute_export_form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(mmqgis_attribute_export_form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(mmqgis_attribute_export_form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label = QtWidgets.QLabel(mmqgis_attribute_export_form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.output_csv_name = gui.QgsFileWidget(mmqgis_attribute_export_form)
        self.output_csv_name.setObjectName("output_csv_name")
        self.verticalLayout.addWidget(self.output_csv_name)
        self.status = QtWidgets.QProgressBar(mmqgis_attribute_export_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(mmqgis_attribute_export_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_attribute_export_form)
        self.buttonBox.accepted.connect(mmqgis_attribute_export_form.accept)
        self.buttonBox.rejected.connect(mmqgis_attribute_export_form.reject)
        QtCore.QMetaObject.connectSlotsByName(mmqgis_attribute_export_form)
        mmqgis_attribute_export_form.setTabOrder(self.input_layer_name, self.attributes)
        mmqgis_attribute_export_form.setTabOrder(self.attributes, self.field_delimiter)
        mmqgis_attribute_export_form.setTabOrder(self.field_delimiter, self.line_terminator)
        mmqgis_attribute_export_form.setTabOrder(self.line_terminator, self.buttonBox)

    def retranslateUi(self, mmqgis_attribute_export_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_attribute_export_form.setWindowTitle(_translate("mmqgis_attribute_export_form", "Export Attributes"))
        self.label_4.setText(_translate("mmqgis_attribute_export_form", "Input Layer"))
        self.label_2.setText(_translate("mmqgis_attribute_export_form", "Attributes"))
        __sortingEnabled = self.attributes.isSortingEnabled()
        self.attributes.setSortingEnabled(False)
        item = self.attributes.item(0)
        item.setText(_translate("mmqgis_attribute_export_form", "Alpha"))
        item = self.attributes.item(1)
        item.setText(_translate("mmqgis_attribute_export_form", "Beta"))
        item = self.attributes.item(2)
        item.setText(_translate("mmqgis_attribute_export_form", "Gamma"))
        item = self.attributes.item(3)
        item.setText(_translate("mmqgis_attribute_export_form", "Delta"))
        item = self.attributes.item(4)
        item.setText(_translate("mmqgis_attribute_export_form", "Epsilon"))
        self.attributes.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("mmqgis_attribute_export_form", "Delimiter"))
        self.label_6.setText(_translate("mmqgis_attribute_export_form", "Decimal Mark"))
        self.label_5.setText(_translate("mmqgis_attribute_export_form", "Line Terminator"))
        self.label.setText(_translate("mmqgis_attribute_export_form", "Output CSV File"))

from qgis import gui
