# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/mmqgis_animate_location_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mmqgis_animate_location_form(object):
    def setupUi(self, mmqgis_animate_location_form):
        mmqgis_animate_location_form.setObjectName("mmqgis_animate_location_form")
        mmqgis_animate_location_form.setWindowModality(QtCore.Qt.ApplicationModal)
        mmqgis_animate_location_form.setEnabled(True)
        mmqgis_animate_location_form.resize(527, 313)
        mmqgis_animate_location_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_animate_location_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(mmqgis_animate_location_form)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.print_layout = QtWidgets.QComboBox(mmqgis_animate_location_form)
        self.print_layout.setObjectName("print_layout")
        self.verticalLayout.addWidget(self.print_layout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.source_layer_name = QtWidgets.QComboBox(mmqgis_animate_location_form)
        self.source_layer_name.setObjectName("source_layer_name")
        self.gridLayout.addWidget(self.source_layer_name, 1, 0, 1, 1)
        self.source_key_field = QtWidgets.QComboBox(mmqgis_animate_location_form)
        self.source_key_field.setObjectName("source_key_field")
        self.gridLayout.addWidget(self.source_key_field, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(mmqgis_animate_location_form)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.destination_layer_name = QtWidgets.QComboBox(mmqgis_animate_location_form)
        self.destination_layer_name.setObjectName("destination_layer_name")
        self.gridLayout.addWidget(self.destination_layer_name, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(mmqgis_animate_location_form)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(mmqgis_animate_location_form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(mmqgis_animate_location_form)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.destination_key_field = QtWidgets.QComboBox(mmqgis_animate_location_form)
        self.destination_key_field.setObjectName("destination_key_field")
        self.gridLayout.addWidget(self.destination_key_field, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_7 = QtWidgets.QLabel(mmqgis_animate_location_form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.frame_count = QtWidgets.QLineEdit(mmqgis_animate_location_form)
        self.frame_count.setReadOnly(False)
        self.frame_count.setObjectName("frame_count")
        self.verticalLayout.addWidget(self.frame_count)
        self.label = QtWidgets.QLabel(mmqgis_animate_location_form)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_directory = gui.QgsFileWidget(mmqgis_animate_location_form)
        self.frame_directory.setObjectName("frame_directory")
        self.verticalLayout.addWidget(self.frame_directory)
        self.status = QtWidgets.QProgressBar(mmqgis_animate_location_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(mmqgis_animate_location_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_animate_location_form)
        self.buttonBox.accepted.connect(mmqgis_animate_location_form.accept)
        self.buttonBox.rejected.connect(mmqgis_animate_location_form.reject)
        QtCore.QMetaObject.connectSlotsByName(mmqgis_animate_location_form)

    def retranslateUi(self, mmqgis_animate_location_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_animate_location_form.setWindowTitle(_translate("mmqgis_animate_location_form", "Animate Location"))
        self.label_5.setText(_translate("mmqgis_animate_location_form", "Print Layout"))
        self.label_4.setText(_translate("mmqgis_animate_location_form", "Source Layer"))
        self.label_6.setText(_translate("mmqgis_animate_location_form", "Source Key Field"))
        self.label_2.setText(_translate("mmqgis_animate_location_form", "Destination Layer"))
        self.label_9.setText(_translate("mmqgis_animate_location_form", "Destination Key Field"))
        self.label_7.setText(_translate("mmqgis_animate_location_form", "Frame Count"))
        self.frame_count.setText(_translate("mmqgis_animate_location_form", "50"))
        self.label.setText(_translate("mmqgis_animate_location_form", "Frame Image Output Directory"))

from qgis import gui
