# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/mmqgis_buffers_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mmqgis_buffers_form(object):
    def setupUi(self, mmqgis_buffers_form):
        mmqgis_buffers_form.setObjectName("mmqgis_buffers_form")
        mmqgis_buffers_form.setWindowModality(QtCore.Qt.ApplicationModal)
        mmqgis_buffers_form.setEnabled(True)
        mmqgis_buffers_form.resize(456, 340)
        mmqgis_buffers_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_buffers_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(mmqgis_buffers_form)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.input_layer_name = QtWidgets.QComboBox(mmqgis_buffers_form)
        self.input_layer_name.setObjectName("input_layer_name")
        self.verticalLayout.addWidget(self.input_layer_name)
        self.selected_only = QtWidgets.QCheckBox(mmqgis_buffers_form)
        self.selected_only.setObjectName("selected_only")
        self.verticalLayout.addWidget(self.selected_only)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(mmqgis_buffers_form)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(mmqgis_buffers_form)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(mmqgis_buffers_form)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.radius_attribute = QtWidgets.QComboBox(mmqgis_buffers_form)
        self.radius_attribute.setObjectName("radius_attribute")
        self.gridLayout.addWidget(self.radius_attribute, 1, 0, 1, 1)
        self.radius = QtWidgets.QLineEdit(mmqgis_buffers_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radius.sizePolicy().hasHeightForWidth())
        self.radius.setSizePolicy(sizePolicy)
        self.radius.setObjectName("radius")
        self.gridLayout.addWidget(self.radius, 1, 1, 1, 1)
        self.radius_unit = QtWidgets.QComboBox(mmqgis_buffers_form)
        self.radius_unit.setObjectName("radius_unit")
        self.gridLayout.addWidget(self.radius_unit, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(mmqgis_buffers_form)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(mmqgis_buffers_form)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.edges_attribute = QtWidgets.QComboBox(mmqgis_buffers_form)
        self.edges_attribute.setObjectName("edges_attribute")
        self.gridLayout_2.addWidget(self.edges_attribute, 1, 0, 1, 1)
        self.edge_count = QtWidgets.QComboBox(mmqgis_buffers_form)
        self.edge_count.setObjectName("edge_count")
        self.gridLayout_2.addWidget(self.edge_count, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(mmqgis_buffers_form)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.rotation_attribute = QtWidgets.QComboBox(mmqgis_buffers_form)
        self.rotation_attribute.setObjectName("rotation_attribute")
        self.gridLayout_3.addWidget(self.rotation_attribute, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(mmqgis_buffers_form)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 1, 1, 1)
        self.rotation_degrees = QtWidgets.QLineEdit(mmqgis_buffers_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotation_degrees.sizePolicy().hasHeightForWidth())
        self.rotation_degrees.setSizePolicy(sizePolicy)
        self.rotation_degrees.setObjectName("rotation_degrees")
        self.gridLayout_3.addWidget(self.rotation_degrees, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.label = QtWidgets.QLabel(mmqgis_buffers_form)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.output_file_name = gui.QgsFileWidget(mmqgis_buffers_form)
        self.output_file_name.setObjectName("output_file_name")
        self.verticalLayout.addWidget(self.output_file_name)
        self.status = QtWidgets.QProgressBar(mmqgis_buffers_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(mmqgis_buffers_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_buffers_form)
        self.buttonBox.accepted.connect(mmqgis_buffers_form.accept)
        self.buttonBox.rejected.connect(mmqgis_buffers_form.reject)
        QtCore.QMetaObject.connectSlotsByName(mmqgis_buffers_form)
        mmqgis_buffers_form.setTabOrder(self.input_layer_name, self.radius_unit)
        mmqgis_buffers_form.setTabOrder(self.radius_unit, self.edges_attribute)
        mmqgis_buffers_form.setTabOrder(self.edges_attribute, self.radius)
        mmqgis_buffers_form.setTabOrder(self.radius, self.radius_attribute)
        mmqgis_buffers_form.setTabOrder(self.radius_attribute, self.selected_only)
        mmqgis_buffers_form.setTabOrder(self.selected_only, self.buttonBox)

    def retranslateUi(self, mmqgis_buffers_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_buffers_form.setWindowTitle(_translate("mmqgis_buffers_form", "Create Buffers"))
        self.label_4.setText(_translate("mmqgis_buffers_form", "Input Layer Name"))
        self.selected_only.setText(_translate("mmqgis_buffers_form", "Selected Features Only"))
        self.label_8.setText(_translate("mmqgis_buffers_form", "Fixed Radius"))
        self.label_9.setText(_translate("mmqgis_buffers_form", "Radius Unit"))
        self.label_7.setText(_translate("mmqgis_buffers_form", "Radius Attribute"))
        self.label_10.setText(_translate("mmqgis_buffers_form", "Fixed Number of Edges"))
        self.label_6.setText(_translate("mmqgis_buffers_form", "Edges Attribute"))
        self.label_11.setText(_translate("mmqgis_buffers_form", "Rotation Attribute"))
        self.label_12.setText(_translate("mmqgis_buffers_form", "Fixed Rotation (Degrees)"))
        self.label.setText(_translate("mmqgis_buffers_form", "Output File Name"))

from qgis import gui
