# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/mmqgis_float_to_text_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mmqgis_float_to_text_form(object):
    def setupUi(self, mmqgis_float_to_text_form):
        mmqgis_float_to_text_form.setObjectName("mmqgis_float_to_text_form")
        mmqgis_float_to_text_form.setWindowModality(QtCore.Qt.ApplicationModal)
        mmqgis_float_to_text_form.setEnabled(True)
        mmqgis_float_to_text_form.resize(553, 503)
        mmqgis_float_to_text_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_float_to_text_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(mmqgis_float_to_text_form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.input_layer_name = QtWidgets.QComboBox(mmqgis_float_to_text_form)
        self.input_layer_name.setObjectName("input_layer_name")
        self.verticalLayout.addWidget(self.input_layer_name)
        self.label_5 = QtWidgets.QLabel(mmqgis_float_to_text_form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.attributes = QtWidgets.QListWidget(mmqgis_float_to_text_form)
        self.attributes.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.attributes.setObjectName("attributes")
        self.verticalLayout.addWidget(self.attributes)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.separator = QtWidgets.QComboBox(mmqgis_float_to_text_form)
        self.separator.setObjectName("separator")
        self.separator.addItem("")
        self.separator.addItem("")
        self.separator.addItem("")
        self.gridLayout_2.addWidget(self.separator, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(mmqgis_float_to_text_form)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(mmqgis_float_to_text_form)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.decimals = QtWidgets.QComboBox(mmqgis_float_to_text_form)
        self.decimals.setObjectName("decimals")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.decimals.addItem("")
        self.gridLayout_2.addWidget(self.decimals, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(mmqgis_float_to_text_form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.multiplier = QtWidgets.QLineEdit(mmqgis_float_to_text_form)
        self.multiplier.setObjectName("multiplier")
        self.gridLayout_2.addWidget(self.multiplier, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(mmqgis_float_to_text_form)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(mmqgis_float_to_text_form)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.prefix = QtWidgets.QLineEdit(mmqgis_float_to_text_form)
        self.prefix.setObjectName("prefix")
        self.gridLayout_3.addWidget(self.prefix, 1, 0, 1, 1)
        self.suffix = QtWidgets.QLineEdit(mmqgis_float_to_text_form)
        self.suffix.setObjectName("suffix")
        self.gridLayout_3.addWidget(self.suffix, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.label = QtWidgets.QLabel(mmqgis_float_to_text_form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.output_file_name = gui.QgsFileWidget(mmqgis_float_to_text_form)
        self.output_file_name.setObjectName("output_file_name")
        self.verticalLayout.addWidget(self.output_file_name)
        self.status = QtWidgets.QProgressBar(mmqgis_float_to_text_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(mmqgis_float_to_text_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_float_to_text_form)
        self.buttonBox.accepted.connect(mmqgis_float_to_text_form.accept)
        self.buttonBox.rejected.connect(mmqgis_float_to_text_form.reject)
        QtCore.QMetaObject.connectSlotsByName(mmqgis_float_to_text_form)
        mmqgis_float_to_text_form.setTabOrder(self.input_layer_name, self.attributes)
        mmqgis_float_to_text_form.setTabOrder(self.attributes, self.buttonBox)

    def retranslateUi(self, mmqgis_float_to_text_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_float_to_text_form.setWindowTitle(_translate("mmqgis_float_to_text_form", "Float to Text"))
        self.label_4.setText(_translate("mmqgis_float_to_text_form", "Input Layer Name"))
        self.label_5.setText(_translate("mmqgis_float_to_text_form", "Fields to Convert"))
        self.separator.setItemText(0, _translate("mmqgis_float_to_text_form", "None"))
        self.separator.setItemText(1, _translate("mmqgis_float_to_text_form", "Comma"))
        self.separator.setItemText(2, _translate("mmqgis_float_to_text_form", "Space"))
        self.label_6.setText(_translate("mmqgis_float_to_text_form", "000\'s Separator"))
        self.label_7.setText(_translate("mmqgis_float_to_text_form", "Decimal Places"))
        self.decimals.setItemText(0, _translate("mmqgis_float_to_text_form", "0"))
        self.decimals.setItemText(1, _translate("mmqgis_float_to_text_form", "1"))
        self.decimals.setItemText(2, _translate("mmqgis_float_to_text_form", "2"))
        self.decimals.setItemText(3, _translate("mmqgis_float_to_text_form", "3"))
        self.decimals.setItemText(4, _translate("mmqgis_float_to_text_form", "4"))
        self.decimals.setItemText(5, _translate("mmqgis_float_to_text_form", "5"))
        self.decimals.setItemText(6, _translate("mmqgis_float_to_text_form", "6"))
        self.decimals.setItemText(7, _translate("mmqgis_float_to_text_form", "7"))
        self.decimals.setItemText(8, _translate("mmqgis_float_to_text_form", "8"))
        self.decimals.setItemText(9, _translate("mmqgis_float_to_text_form", "9"))
        self.decimals.setItemText(10, _translate("mmqgis_float_to_text_form", "10"))
        self.decimals.setItemText(11, _translate("mmqgis_float_to_text_form", "11"))
        self.decimals.setItemText(12, _translate("mmqgis_float_to_text_form", "12"))
        self.label_2.setText(_translate("mmqgis_float_to_text_form", "Multiplier"))
        self.label_9.setText(_translate("mmqgis_float_to_text_form", "Suffix"))
        self.label_8.setText(_translate("mmqgis_float_to_text_form", "Prefix"))
        self.label.setText(_translate("mmqgis_float_to_text_form", "Output File Name"))

from qgis import gui
